### Recuperar todas las películas

GET http://localhost:1234/movies

### Película por id
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

### Pelíclas por género
GET http://localhost:1234/movies?genre=biography
 

### Crear una pelicula con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "Película DYAN WAV",
  "year": 2008,
  "director": "DYAN WAV",
  "duration": 152,
  "poster": "https://unavatar.io/dyanwav",
  "genre": [
    "Action",
    "Crime",
    "Drama"
  ]
}

### Actualizar una pelicula
PATCH http://localhost:1234/movies/ccc67966-5e7c-44d8-b9f9-f403c517bfdc
Content-Type: application/json

{
  "title": "DYANWAV PELICULA EDITADADADADADAD",
  "duration": 1234
}


